workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      java: 17

    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/apk/release/app-release.apk
